### PR TITLE
QoS - ugly fix, but hopefully it is working as intended (ISSUE #1)

### LINKED ISSUE #1: Incorrect statistics in QOS
QOS is not filtering on claimed students anymore. We only want to count students who are waiting a teacher to claim their request.

### PR DESCRIPTION
**Pull request by Olofasenius**
Fixes #1

### CODE REVIEW

**Comment by Olofasenius** [comment]
Could argue that the methods isActiveAndClaimed is not the best boolean check, maybe it should be limited to just "!isClaimed".

Decision based upon the already existing method isActiveAndClaimed in helpRequest-class. Should not impact since all objects in pending-list should be active by earlier checks, so the true-ness should be trivial for that case. leaving the decision to be made by the "isClaimed" variable

**Review by JonasNorlinder — COMMENTED** [review]
Looks good to me 🎉. Have you tested it as well?

**Comment by Olofasenius** [comment]
No testing done, building dev env didn't work at my machine for some reason

**Comment by JonasNorlinder** [comment]
> No testing done, building dev env didn't work at my machine for some reason

Did you see https://bubify.github.io/development/? Otherwise I can test later this week

**Comment by Olofasenius** [comment]
Yes, followed the doc, didn't work, if u could test, would be great!

**Review by JonasNorlinder — APPROVED** [review]
Tested code and it seems correct

**Pull request merged**
